// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package redis_mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRedisClientInterface creates a new instance of MockRedisClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedisClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedisClientInterface {
	mock := &MockRedisClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRedisClientInterface is an autogenerated mock type for the RedisClientInterface type
type MockRedisClientInterface struct {
	mock.Mock
}

type MockRedisClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedisClientInterface) EXPECT() *MockRedisClientInterface_Expecter {
	return &MockRedisClientInterface_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockRedisClientInterface
func (_mock *MockRedisClientInterface) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedisClientInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRedisClientInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRedisClientInterface_Expecter) Delete(ctx interface{}, key interface{}) *MockRedisClientInterface_Delete_Call {
	return &MockRedisClientInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockRedisClientInterface_Delete_Call) Run(run func(ctx context.Context, key string)) *MockRedisClientInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRedisClientInterface_Delete_Call) Return(err error) *MockRedisClientInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedisClientInterface_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockRedisClientInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRedisClientInterface
func (_mock *MockRedisClientInterface) Get(ctx context.Context, key string, dest interface{}) error {
	ret := _mock.Called(ctx, key, dest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = returnFunc(ctx, key, dest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedisClientInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRedisClientInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - dest interface{}
func (_e *MockRedisClientInterface_Expecter) Get(ctx interface{}, key interface{}, dest interface{}) *MockRedisClientInterface_Get_Call {
	return &MockRedisClientInterface_Get_Call{Call: _e.mock.On("Get", ctx, key, dest)}
}

func (_c *MockRedisClientInterface_Get_Call) Run(run func(ctx context.Context, key string, dest interface{})) *MockRedisClientInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRedisClientInterface_Get_Call) Return(err error) *MockRedisClientInterface_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedisClientInterface_Get_Call) RunAndReturn(run func(ctx context.Context, key string, dest interface{}) error) *MockRedisClientInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Hit provides a mock function for the type MockRedisClientInterface
func (_mock *MockRedisClientInterface) Hit() {
	_mock.Called()
	return
}

// MockRedisClientInterface_Hit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hit'
type MockRedisClientInterface_Hit_Call struct {
	*mock.Call
}

// Hit is a helper method to define mock.On call
func (_e *MockRedisClientInterface_Expecter) Hit() *MockRedisClientInterface_Hit_Call {
	return &MockRedisClientInterface_Hit_Call{Call: _e.mock.On("Hit")}
}

func (_c *MockRedisClientInterface_Hit_Call) Run(run func()) *MockRedisClientInterface_Hit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRedisClientInterface_Hit_Call) Return() *MockRedisClientInterface_Hit_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRedisClientInterface_Hit_Call) RunAndReturn(run func()) *MockRedisClientInterface_Hit_Call {
	_c.Run(run)
	return _c
}

// Miss provides a mock function for the type MockRedisClientInterface
func (_mock *MockRedisClientInterface) Miss() {
	_mock.Called()
	return
}

// MockRedisClientInterface_Miss_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Miss'
type MockRedisClientInterface_Miss_Call struct {
	*mock.Call
}

// Miss is a helper method to define mock.On call
func (_e *MockRedisClientInterface_Expecter) Miss() *MockRedisClientInterface_Miss_Call {
	return &MockRedisClientInterface_Miss_Call{Call: _e.mock.On("Miss")}
}

func (_c *MockRedisClientInterface_Miss_Call) Run(run func()) *MockRedisClientInterface_Miss_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRedisClientInterface_Miss_Call) Return() *MockRedisClientInterface_Miss_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRedisClientInterface_Miss_Call) RunAndReturn(run func()) *MockRedisClientInterface_Miss_Call {
	_c.Run(run)
	return _c
}

// Set provides a mock function for the type MockRedisClientInterface
func (_mock *MockRedisClientInterface) Set(ctx context.Context, key string, value interface{}, expiration time.Duration) error {
	ret := _mock.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedisClientInterface_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockRedisClientInterface_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - expiration time.Duration
func (_e *MockRedisClientInterface_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *MockRedisClientInterface_Set_Call {
	return &MockRedisClientInterface_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *MockRedisClientInterface_Set_Call) Run(run func(ctx context.Context, key string, value interface{}, expiration time.Duration)) *MockRedisClientInterface_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRedisClientInterface_Set_Call) Return(err error) *MockRedisClientInterface_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedisClientInterface_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value interface{}, expiration time.Duration) error) *MockRedisClientInterface_Set_Call {
	_c.Call.Return(run)
	return _c
}
