// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services_mocks

import (
	"context"
	"delivery-system/internal/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGeolocationServiceInterface creates a new instance of MockGeolocationServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGeolocationServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGeolocationServiceInterface {
	mock := &MockGeolocationServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGeolocationServiceInterface is an autogenerated mock type for the GeolocationServiceInterface type
type MockGeolocationServiceInterface struct {
	mock.Mock
}

type MockGeolocationServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGeolocationServiceInterface) EXPECT() *MockGeolocationServiceInterface_Expecter {
	return &MockGeolocationServiceInterface_Expecter{mock: &_m.Mock}
}

// CacheResults provides a mock function for the type MockGeolocationServiceInterface
func (_mock *MockGeolocationServiceInterface) CacheResults(coordinates [][2]float64, distance float64, order *models.Order) {
	_mock.Called(coordinates, distance, order)
	return
}

// MockGeolocationServiceInterface_CacheResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CacheResults'
type MockGeolocationServiceInterface_CacheResults_Call struct {
	*mock.Call
}

// CacheResults is a helper method to define mock.On call
//   - coordinates [][2]float64
//   - distance float64
//   - order *models.Order
func (_e *MockGeolocationServiceInterface_Expecter) CacheResults(coordinates interface{}, distance interface{}, order interface{}) *MockGeolocationServiceInterface_CacheResults_Call {
	return &MockGeolocationServiceInterface_CacheResults_Call{Call: _e.mock.On("CacheResults", coordinates, distance, order)}
}

func (_c *MockGeolocationServiceInterface_CacheResults_Call) Run(run func(coordinates [][2]float64, distance float64, order *models.Order)) *MockGeolocationServiceInterface_CacheResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 [][2]float64
		if args[0] != nil {
			arg0 = args[0].([][2]float64)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		var arg2 *models.Order
		if args[2] != nil {
			arg2 = args[2].(*models.Order)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGeolocationServiceInterface_CacheResults_Call) Return() *MockGeolocationServiceInterface_CacheResults_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGeolocationServiceInterface_CacheResults_Call) RunAndReturn(run func(coordinates [][2]float64, distance float64, order *models.Order)) *MockGeolocationServiceInterface_CacheResults_Call {
	_c.Run(run)
	return _c
}

// GetCoordinates provides a mock function for the type MockGeolocationServiceInterface
func (_mock *MockGeolocationServiceInterface) GetCoordinates(address string) (float64, float64, error) {
	ret := _mock.Called(address)

	if len(ret) == 0 {
		panic("no return value specified for GetCoordinates")
	}

	var r0 float64
	var r1 float64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (float64, float64, error)); ok {
		return returnFunc(address)
	}
	if returnFunc, ok := ret.Get(0).(func(string) float64); ok {
		r0 = returnFunc(address)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(string) float64); ok {
		r1 = returnFunc(address)
	} else {
		r1 = ret.Get(1).(float64)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(address)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGeolocationServiceInterface_GetCoordinates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoordinates'
type MockGeolocationServiceInterface_GetCoordinates_Call struct {
	*mock.Call
}

// GetCoordinates is a helper method to define mock.On call
//   - address string
func (_e *MockGeolocationServiceInterface_Expecter) GetCoordinates(address interface{}) *MockGeolocationServiceInterface_GetCoordinates_Call {
	return &MockGeolocationServiceInterface_GetCoordinates_Call{Call: _e.mock.On("GetCoordinates", address)}
}

func (_c *MockGeolocationServiceInterface_GetCoordinates_Call) Run(run func(address string)) *MockGeolocationServiceInterface_GetCoordinates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGeolocationServiceInterface_GetCoordinates_Call) Return(f float64, f1 float64, err error) *MockGeolocationServiceInterface_GetCoordinates_Call {
	_c.Call.Return(f, f1, err)
	return _c
}

func (_c *MockGeolocationServiceInterface_GetCoordinates_Call) RunAndReturn(run func(address string) (float64, float64, error)) *MockGeolocationServiceInterface_GetCoordinates_Call {
	_c.Call.Return(run)
	return _c
}

// MakeRoute provides a mock function for the type MockGeolocationServiceInterface
func (_mock *MockGeolocationServiceInterface) MakeRoute(coordinates [][2]float64) (float64, error) {
	ret := _mock.Called(coordinates)

	if len(ret) == 0 {
		panic("no return value specified for MakeRoute")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([][2]float64) (float64, error)); ok {
		return returnFunc(coordinates)
	}
	if returnFunc, ok := ret.Get(0).(func([][2]float64) float64); ok {
		r0 = returnFunc(coordinates)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func([][2]float64) error); ok {
		r1 = returnFunc(coordinates)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGeolocationServiceInterface_MakeRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeRoute'
type MockGeolocationServiceInterface_MakeRoute_Call struct {
	*mock.Call
}

// MakeRoute is a helper method to define mock.On call
//   - coordinates [][2]float64
func (_e *MockGeolocationServiceInterface_Expecter) MakeRoute(coordinates interface{}) *MockGeolocationServiceInterface_MakeRoute_Call {
	return &MockGeolocationServiceInterface_MakeRoute_Call{Call: _e.mock.On("MakeRoute", coordinates)}
}

func (_c *MockGeolocationServiceInterface_MakeRoute_Call) Run(run func(coordinates [][2]float64)) *MockGeolocationServiceInterface_MakeRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 [][2]float64
		if args[0] != nil {
			arg0 = args[0].([][2]float64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGeolocationServiceInterface_MakeRoute_Call) Return(f float64, err error) *MockGeolocationServiceInterface_MakeRoute_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MockGeolocationServiceInterface_MakeRoute_Call) RunAndReturn(run func(coordinates [][2]float64) (float64, error)) *MockGeolocationServiceInterface_MakeRoute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderServiceInterface creates a new instance of MockOrderServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderServiceInterface {
	mock := &MockOrderServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderServiceInterface is an autogenerated mock type for the OrderServiceInterface type
type MockOrderServiceInterface struct {
	mock.Mock
}

type MockOrderServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderServiceInterface) EXPECT() *MockOrderServiceInterface_Expecter {
	return &MockOrderServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function for the type MockOrderServiceInterface
func (_mock *MockOrderServiceInterface) CreateOrder(req *models.CreateOrderRequest) (*models.Order, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.CreateOrderRequest) (*models.Order, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.CreateOrderRequest) *models.Order); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*models.CreateOrderRequest) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderServiceInterface_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockOrderServiceInterface_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - req *models.CreateOrderRequest
func (_e *MockOrderServiceInterface_Expecter) CreateOrder(req interface{}) *MockOrderServiceInterface_CreateOrder_Call {
	return &MockOrderServiceInterface_CreateOrder_Call{Call: _e.mock.On("CreateOrder", req)}
}

func (_c *MockOrderServiceInterface_CreateOrder_Call) Run(run func(req *models.CreateOrderRequest)) *MockOrderServiceInterface_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.CreateOrderRequest
		if args[0] != nil {
			arg0 = args[0].(*models.CreateOrderRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderServiceInterface_CreateOrder_Call) Return(order *models.Order, err error) *MockOrderServiceInterface_CreateOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderServiceInterface_CreateOrder_Call) RunAndReturn(run func(req *models.CreateOrderRequest) (*models.Order, error)) *MockOrderServiceInterface_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type MockOrderServiceInterface
func (_mock *MockOrderServiceInterface) GetOrder(orderID uuid.UUID) (*models.Order, error) {
	ret := _mock.Called(orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*models.Order, error)); ok {
		return returnFunc(orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *models.Order); ok {
		r0 = returnFunc(orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderServiceInterface_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockOrderServiceInterface_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - orderID uuid.UUID
func (_e *MockOrderServiceInterface_Expecter) GetOrder(orderID interface{}) *MockOrderServiceInterface_GetOrder_Call {
	return &MockOrderServiceInterface_GetOrder_Call{Call: _e.mock.On("GetOrder", orderID)}
}

func (_c *MockOrderServiceInterface_GetOrder_Call) Run(run func(orderID uuid.UUID)) *MockOrderServiceInterface_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderServiceInterface_GetOrder_Call) Return(order *models.Order, err error) *MockOrderServiceInterface_GetOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderServiceInterface_GetOrder_Call) RunAndReturn(run func(orderID uuid.UUID) (*models.Order, error)) *MockOrderServiceInterface_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrders provides a mock function for the type MockOrderServiceInterface
func (_mock *MockOrderServiceInterface) GetOrders(status *models.OrderStatus, courierID *uuid.UUID, limit int, offset int) ([]*models.Order, error) {
	ret := _mock.Called(status, courierID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 []*models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.OrderStatus, *uuid.UUID, int, int) ([]*models.Order, error)); ok {
		return returnFunc(status, courierID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.OrderStatus, *uuid.UUID, int, int) []*models.Order); ok {
		r0 = returnFunc(status, courierID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*models.OrderStatus, *uuid.UUID, int, int) error); ok {
		r1 = returnFunc(status, courierID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderServiceInterface_GetOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrders'
type MockOrderServiceInterface_GetOrders_Call struct {
	*mock.Call
}

// GetOrders is a helper method to define mock.On call
//   - status *models.OrderStatus
//   - courierID *uuid.UUID
//   - limit int
//   - offset int
func (_e *MockOrderServiceInterface_Expecter) GetOrders(status interface{}, courierID interface{}, limit interface{}, offset interface{}) *MockOrderServiceInterface_GetOrders_Call {
	return &MockOrderServiceInterface_GetOrders_Call{Call: _e.mock.On("GetOrders", status, courierID, limit, offset)}
}

func (_c *MockOrderServiceInterface_GetOrders_Call) Run(run func(status *models.OrderStatus, courierID *uuid.UUID, limit int, offset int)) *MockOrderServiceInterface_GetOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.OrderStatus
		if args[0] != nil {
			arg0 = args[0].(*models.OrderStatus)
		}
		var arg1 *uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrderServiceInterface_GetOrders_Call) Return(orders []*models.Order, err error) *MockOrderServiceInterface_GetOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderServiceInterface_GetOrders_Call) RunAndReturn(run func(status *models.OrderStatus, courierID *uuid.UUID, limit int, offset int) ([]*models.Order, error)) *MockOrderServiceInterface_GetOrders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderStatus provides a mock function for the type MockOrderServiceInterface
func (_mock *MockOrderServiceInterface) UpdateOrderStatus(orderID uuid.UUID, req *models.UpdateOrderStatusRequest) error {
	ret := _mock.Called(orderID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, *models.UpdateOrderStatusRequest) error); ok {
		r0 = returnFunc(orderID, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderServiceInterface_UpdateOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderStatus'
type MockOrderServiceInterface_UpdateOrderStatus_Call struct {
	*mock.Call
}

// UpdateOrderStatus is a helper method to define mock.On call
//   - orderID uuid.UUID
//   - req *models.UpdateOrderStatusRequest
func (_e *MockOrderServiceInterface_Expecter) UpdateOrderStatus(orderID interface{}, req interface{}) *MockOrderServiceInterface_UpdateOrderStatus_Call {
	return &MockOrderServiceInterface_UpdateOrderStatus_Call{Call: _e.mock.On("UpdateOrderStatus", orderID, req)}
}

func (_c *MockOrderServiceInterface_UpdateOrderStatus_Call) Run(run func(orderID uuid.UUID, req *models.UpdateOrderStatusRequest)) *MockOrderServiceInterface_UpdateOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 *models.UpdateOrderStatusRequest
		if args[1] != nil {
			arg1 = args[1].(*models.UpdateOrderStatusRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderServiceInterface_UpdateOrderStatus_Call) Return(err error) *MockOrderServiceInterface_UpdateOrderStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderServiceInterface_UpdateOrderStatus_Call) RunAndReturn(run func(orderID uuid.UUID, req *models.UpdateOrderStatusRequest) error) *MockOrderServiceInterface_UpdateOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReviewServiceInterface creates a new instance of MockReviewServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewServiceInterface {
	mock := &MockReviewServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReviewServiceInterface is an autogenerated mock type for the ReviewServiceInterface type
type MockReviewServiceInterface struct {
	mock.Mock
}

type MockReviewServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewServiceInterface) EXPECT() *MockReviewServiceInterface_Expecter {
	return &MockReviewServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateReview provides a mock function for the type MockReviewServiceInterface
func (_mock *MockReviewServiceInterface) CreateReview(req *models.CreateReviewRequest, order *models.Order) (*models.Review, error) {
	ret := _mock.Called(req, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateReview")
	}

	var r0 *models.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.CreateReviewRequest, *models.Order) (*models.Review, error)); ok {
		return returnFunc(req, order)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.CreateReviewRequest, *models.Order) *models.Review); ok {
		r0 = returnFunc(req, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*models.CreateReviewRequest, *models.Order) error); ok {
		r1 = returnFunc(req, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewServiceInterface_CreateReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReview'
type MockReviewServiceInterface_CreateReview_Call struct {
	*mock.Call
}

// CreateReview is a helper method to define mock.On call
//   - req *models.CreateReviewRequest
//   - order *models.Order
func (_e *MockReviewServiceInterface_Expecter) CreateReview(req interface{}, order interface{}) *MockReviewServiceInterface_CreateReview_Call {
	return &MockReviewServiceInterface_CreateReview_Call{Call: _e.mock.On("CreateReview", req, order)}
}

func (_c *MockReviewServiceInterface_CreateReview_Call) Run(run func(req *models.CreateReviewRequest, order *models.Order)) *MockReviewServiceInterface_CreateReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.CreateReviewRequest
		if args[0] != nil {
			arg0 = args[0].(*models.CreateReviewRequest)
		}
		var arg1 *models.Order
		if args[1] != nil {
			arg1 = args[1].(*models.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewServiceInterface_CreateReview_Call) Return(review *models.Review, err error) *MockReviewServiceInterface_CreateReview_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockReviewServiceInterface_CreateReview_Call) RunAndReturn(run func(req *models.CreateReviewRequest, order *models.Order) (*models.Review, error)) *MockReviewServiceInterface_CreateReview_Call {
	_c.Call.Return(run)
	return _c
}

// GetReviews provides a mock function for the type MockReviewServiceInterface
func (_mock *MockReviewServiceInterface) GetReviews(courierID uuid.UUID) ([]*models.Review, error) {
	ret := _mock.Called(courierID)

	if len(ret) == 0 {
		panic("no return value specified for GetReviews")
	}

	var r0 []*models.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) ([]*models.Review, error)); ok {
		return returnFunc(courierID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) []*models.Review); ok {
		r0 = returnFunc(courierID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(courierID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewServiceInterface_GetReviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviews'
type MockReviewServiceInterface_GetReviews_Call struct {
	*mock.Call
}

// GetReviews is a helper method to define mock.On call
//   - courierID uuid.UUID
func (_e *MockReviewServiceInterface_Expecter) GetReviews(courierID interface{}) *MockReviewServiceInterface_GetReviews_Call {
	return &MockReviewServiceInterface_GetReviews_Call{Call: _e.mock.On("GetReviews", courierID)}
}

func (_c *MockReviewServiceInterface_GetReviews_Call) Run(run func(courierID uuid.UUID)) *MockReviewServiceInterface_GetReviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewServiceInterface_GetReviews_Call) Return(reviews []*models.Review, err error) *MockReviewServiceInterface_GetReviews_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockReviewServiceInterface_GetReviews_Call) RunAndReturn(run func(courierID uuid.UUID) ([]*models.Review, error)) *MockReviewServiceInterface_GetReviews_Call {
	_c.Call.Return(run)
	return _c
}

// RecalculateRating provides a mock function for the type MockReviewServiceInterface
func (_mock *MockReviewServiceInterface) RecalculateRating(courierID uuid.UUID) error {
	ret := _mock.Called(courierID)

	if len(ret) == 0 {
		panic("no return value specified for RecalculateRating")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(courierID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReviewServiceInterface_RecalculateRating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecalculateRating'
type MockReviewServiceInterface_RecalculateRating_Call struct {
	*mock.Call
}

// RecalculateRating is a helper method to define mock.On call
//   - courierID uuid.UUID
func (_e *MockReviewServiceInterface_Expecter) RecalculateRating(courierID interface{}) *MockReviewServiceInterface_RecalculateRating_Call {
	return &MockReviewServiceInterface_RecalculateRating_Call{Call: _e.mock.On("RecalculateRating", courierID)}
}

func (_c *MockReviewServiceInterface_RecalculateRating_Call) Run(run func(courierID uuid.UUID)) *MockReviewServiceInterface_RecalculateRating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewServiceInterface_RecalculateRating_Call) Return(err error) *MockReviewServiceInterface_RecalculateRating_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReviewServiceInterface_RecalculateRating_Call) RunAndReturn(run func(courierID uuid.UUID) error) *MockReviewServiceInterface_RecalculateRating_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCourierServiceInterface creates a new instance of MockCourierServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCourierServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCourierServiceInterface {
	mock := &MockCourierServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCourierServiceInterface is an autogenerated mock type for the CourierServiceInterface type
type MockCourierServiceInterface struct {
	mock.Mock
}

type MockCourierServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCourierServiceInterface) EXPECT() *MockCourierServiceInterface_Expecter {
	return &MockCourierServiceInterface_Expecter{mock: &_m.Mock}
}

// AssignOrderToCourier provides a mock function for the type MockCourierServiceInterface
func (_mock *MockCourierServiceInterface) AssignOrderToCourier(orderID uuid.UUID, courierID uuid.UUID) error {
	ret := _mock.Called(orderID, courierID)

	if len(ret) == 0 {
		panic("no return value specified for AssignOrderToCourier")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(orderID, courierID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCourierServiceInterface_AssignOrderToCourier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignOrderToCourier'
type MockCourierServiceInterface_AssignOrderToCourier_Call struct {
	*mock.Call
}

// AssignOrderToCourier is a helper method to define mock.On call
//   - orderID uuid.UUID
//   - courierID uuid.UUID
func (_e *MockCourierServiceInterface_Expecter) AssignOrderToCourier(orderID interface{}, courierID interface{}) *MockCourierServiceInterface_AssignOrderToCourier_Call {
	return &MockCourierServiceInterface_AssignOrderToCourier_Call{Call: _e.mock.On("AssignOrderToCourier", orderID, courierID)}
}

func (_c *MockCourierServiceInterface_AssignOrderToCourier_Call) Run(run func(orderID uuid.UUID, courierID uuid.UUID)) *MockCourierServiceInterface_AssignOrderToCourier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCourierServiceInterface_AssignOrderToCourier_Call) Return(err error) *MockCourierServiceInterface_AssignOrderToCourier_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCourierServiceInterface_AssignOrderToCourier_Call) RunAndReturn(run func(orderID uuid.UUID, courierID uuid.UUID) error) *MockCourierServiceInterface_AssignOrderToCourier_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCourier provides a mock function for the type MockCourierServiceInterface
func (_mock *MockCourierServiceInterface) CreateCourier(req *models.CreateCourierRequest) (*models.Courier, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourier")
	}

	var r0 *models.Courier
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.CreateCourierRequest) (*models.Courier, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.CreateCourierRequest) *models.Courier); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Courier)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*models.CreateCourierRequest) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCourierServiceInterface_CreateCourier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCourier'
type MockCourierServiceInterface_CreateCourier_Call struct {
	*mock.Call
}

// CreateCourier is a helper method to define mock.On call
//   - req *models.CreateCourierRequest
func (_e *MockCourierServiceInterface_Expecter) CreateCourier(req interface{}) *MockCourierServiceInterface_CreateCourier_Call {
	return &MockCourierServiceInterface_CreateCourier_Call{Call: _e.mock.On("CreateCourier", req)}
}

func (_c *MockCourierServiceInterface_CreateCourier_Call) Run(run func(req *models.CreateCourierRequest)) *MockCourierServiceInterface_CreateCourier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.CreateCourierRequest
		if args[0] != nil {
			arg0 = args[0].(*models.CreateCourierRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCourierServiceInterface_CreateCourier_Call) Return(courier *models.Courier, err error) *MockCourierServiceInterface_CreateCourier_Call {
	_c.Call.Return(courier, err)
	return _c
}

func (_c *MockCourierServiceInterface_CreateCourier_Call) RunAndReturn(run func(req *models.CreateCourierRequest) (*models.Courier, error)) *MockCourierServiceInterface_CreateCourier_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvailableCouriers provides a mock function for the type MockCourierServiceInterface
func (_mock *MockCourierServiceInterface) GetAvailableCouriers() ([]*models.Courier, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableCouriers")
	}

	var r0 []*models.Courier
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*models.Courier, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*models.Courier); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Courier)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCourierServiceInterface_GetAvailableCouriers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailableCouriers'
type MockCourierServiceInterface_GetAvailableCouriers_Call struct {
	*mock.Call
}

// GetAvailableCouriers is a helper method to define mock.On call
func (_e *MockCourierServiceInterface_Expecter) GetAvailableCouriers() *MockCourierServiceInterface_GetAvailableCouriers_Call {
	return &MockCourierServiceInterface_GetAvailableCouriers_Call{Call: _e.mock.On("GetAvailableCouriers")}
}

func (_c *MockCourierServiceInterface_GetAvailableCouriers_Call) Run(run func()) *MockCourierServiceInterface_GetAvailableCouriers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCourierServiceInterface_GetAvailableCouriers_Call) Return(couriers []*models.Courier, err error) *MockCourierServiceInterface_GetAvailableCouriers_Call {
	_c.Call.Return(couriers, err)
	return _c
}

func (_c *MockCourierServiceInterface_GetAvailableCouriers_Call) RunAndReturn(run func() ([]*models.Courier, error)) *MockCourierServiceInterface_GetAvailableCouriers_Call {
	_c.Call.Return(run)
	return _c
}

// GetCourier provides a mock function for the type MockCourierServiceInterface
func (_mock *MockCourierServiceInterface) GetCourier(courierID uuid.UUID) (*models.Courier, error) {
	ret := _mock.Called(courierID)

	if len(ret) == 0 {
		panic("no return value specified for GetCourier")
	}

	var r0 *models.Courier
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*models.Courier, error)); ok {
		return returnFunc(courierID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *models.Courier); ok {
		r0 = returnFunc(courierID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Courier)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(courierID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCourierServiceInterface_GetCourier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourier'
type MockCourierServiceInterface_GetCourier_Call struct {
	*mock.Call
}

// GetCourier is a helper method to define mock.On call
//   - courierID uuid.UUID
func (_e *MockCourierServiceInterface_Expecter) GetCourier(courierID interface{}) *MockCourierServiceInterface_GetCourier_Call {
	return &MockCourierServiceInterface_GetCourier_Call{Call: _e.mock.On("GetCourier", courierID)}
}

func (_c *MockCourierServiceInterface_GetCourier_Call) Run(run func(courierID uuid.UUID)) *MockCourierServiceInterface_GetCourier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCourierServiceInterface_GetCourier_Call) Return(courier *models.Courier, err error) *MockCourierServiceInterface_GetCourier_Call {
	_c.Call.Return(courier, err)
	return _c
}

func (_c *MockCourierServiceInterface_GetCourier_Call) RunAndReturn(run func(courierID uuid.UUID) (*models.Courier, error)) *MockCourierServiceInterface_GetCourier_Call {
	_c.Call.Return(run)
	return _c
}

// GetCouriers provides a mock function for the type MockCourierServiceInterface
func (_mock *MockCourierServiceInterface) GetCouriers(status *models.CourierStatus, limit int, offset int, ratingSort bool) ([]*models.Courier, error) {
	ret := _mock.Called(status, limit, offset, ratingSort)

	if len(ret) == 0 {
		panic("no return value specified for GetCouriers")
	}

	var r0 []*models.Courier
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.CourierStatus, int, int, bool) ([]*models.Courier, error)); ok {
		return returnFunc(status, limit, offset, ratingSort)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.CourierStatus, int, int, bool) []*models.Courier); ok {
		r0 = returnFunc(status, limit, offset, ratingSort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Courier)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*models.CourierStatus, int, int, bool) error); ok {
		r1 = returnFunc(status, limit, offset, ratingSort)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCourierServiceInterface_GetCouriers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCouriers'
type MockCourierServiceInterface_GetCouriers_Call struct {
	*mock.Call
}

// GetCouriers is a helper method to define mock.On call
//   - status *models.CourierStatus
//   - limit int
//   - offset int
//   - ratingSort bool
func (_e *MockCourierServiceInterface_Expecter) GetCouriers(status interface{}, limit interface{}, offset interface{}, ratingSort interface{}) *MockCourierServiceInterface_GetCouriers_Call {
	return &MockCourierServiceInterface_GetCouriers_Call{Call: _e.mock.On("GetCouriers", status, limit, offset, ratingSort)}
}

func (_c *MockCourierServiceInterface_GetCouriers_Call) Run(run func(status *models.CourierStatus, limit int, offset int, ratingSort bool)) *MockCourierServiceInterface_GetCouriers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.CourierStatus
		if args[0] != nil {
			arg0 = args[0].(*models.CourierStatus)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCourierServiceInterface_GetCouriers_Call) Return(couriers []*models.Courier, err error) *MockCourierServiceInterface_GetCouriers_Call {
	_c.Call.Return(couriers, err)
	return _c
}

func (_c *MockCourierServiceInterface_GetCouriers_Call) RunAndReturn(run func(status *models.CourierStatus, limit int, offset int, ratingSort bool) ([]*models.Courier, error)) *MockCourierServiceInterface_GetCouriers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCourierStatus provides a mock function for the type MockCourierServiceInterface
func (_mock *MockCourierServiceInterface) UpdateCourierStatus(courierID uuid.UUID, req *models.UpdateCourierStatusRequest) error {
	ret := _mock.Called(courierID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCourierStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, *models.UpdateCourierStatusRequest) error); ok {
		r0 = returnFunc(courierID, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCourierServiceInterface_UpdateCourierStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCourierStatus'
type MockCourierServiceInterface_UpdateCourierStatus_Call struct {
	*mock.Call
}

// UpdateCourierStatus is a helper method to define mock.On call
//   - courierID uuid.UUID
//   - req *models.UpdateCourierStatusRequest
func (_e *MockCourierServiceInterface_Expecter) UpdateCourierStatus(courierID interface{}, req interface{}) *MockCourierServiceInterface_UpdateCourierStatus_Call {
	return &MockCourierServiceInterface_UpdateCourierStatus_Call{Call: _e.mock.On("UpdateCourierStatus", courierID, req)}
}

func (_c *MockCourierServiceInterface_UpdateCourierStatus_Call) Run(run func(courierID uuid.UUID, req *models.UpdateCourierStatusRequest)) *MockCourierServiceInterface_UpdateCourierStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 *models.UpdateCourierStatusRequest
		if args[1] != nil {
			arg1 = args[1].(*models.UpdateCourierStatusRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCourierServiceInterface_UpdateCourierStatus_Call) Return(err error) *MockCourierServiceInterface_UpdateCourierStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCourierServiceInterface_UpdateCourierStatus_Call) RunAndReturn(run func(courierID uuid.UUID, req *models.UpdateCourierStatusRequest) error) *MockCourierServiceInterface_UpdateCourierStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKafkaMetricsServiceInterface creates a new instance of MockKafkaMetricsServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKafkaMetricsServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKafkaMetricsServiceInterface {
	mock := &MockKafkaMetricsServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKafkaMetricsServiceInterface is an autogenerated mock type for the KafkaMetricsServiceInterface type
type MockKafkaMetricsServiceInterface struct {
	mock.Mock
}

type MockKafkaMetricsServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKafkaMetricsServiceInterface) EXPECT() *MockKafkaMetricsServiceInterface_Expecter {
	return &MockKafkaMetricsServiceInterface_Expecter{mock: &_m.Mock}
}

// GetStatistics provides a mock function for the type MockKafkaMetricsServiceInterface
func (_mock *MockKafkaMetricsServiceInterface) GetStatistics() *models.KafkaMetricsResponse {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStatistics")
	}

	var r0 *models.KafkaMetricsResponse
	if returnFunc, ok := ret.Get(0).(func() *models.KafkaMetricsResponse); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.KafkaMetricsResponse)
		}
	}
	return r0
}

// MockKafkaMetricsServiceInterface_GetStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatistics'
type MockKafkaMetricsServiceInterface_GetStatistics_Call struct {
	*mock.Call
}

// GetStatistics is a helper method to define mock.On call
func (_e *MockKafkaMetricsServiceInterface_Expecter) GetStatistics() *MockKafkaMetricsServiceInterface_GetStatistics_Call {
	return &MockKafkaMetricsServiceInterface_GetStatistics_Call{Call: _e.mock.On("GetStatistics")}
}

func (_c *MockKafkaMetricsServiceInterface_GetStatistics_Call) Run(run func()) *MockKafkaMetricsServiceInterface_GetStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKafkaMetricsServiceInterface_GetStatistics_Call) Return(kafkaMetricsResponse *models.KafkaMetricsResponse) *MockKafkaMetricsServiceInterface_GetStatistics_Call {
	_c.Call.Return(kafkaMetricsResponse)
	return _c
}

func (_c *MockKafkaMetricsServiceInterface_GetStatistics_Call) RunAndReturn(run func() *models.KafkaMetricsResponse) *MockKafkaMetricsServiceInterface_GetStatistics_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRedisServiceInterface creates a new instance of MockRedisServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedisServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedisServiceInterface {
	mock := &MockRedisServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRedisServiceInterface is an autogenerated mock type for the RedisServiceInterface type
type MockRedisServiceInterface struct {
	mock.Mock
}

type MockRedisServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedisServiceInterface) EXPECT() *MockRedisServiceInterface_Expecter {
	return &MockRedisServiceInterface_Expecter{mock: &_m.Mock}
}

// GetStatistics provides a mock function for the type MockRedisServiceInterface
func (_mock *MockRedisServiceInterface) GetStatistics(ctx context.Context) (*models.RedisMetricsResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStatistics")
	}

	var r0 *models.RedisMetricsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*models.RedisMetricsResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *models.RedisMetricsResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RedisMetricsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRedisServiceInterface_GetStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatistics'
type MockRedisServiceInterface_GetStatistics_Call struct {
	*mock.Call
}

// GetStatistics is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRedisServiceInterface_Expecter) GetStatistics(ctx interface{}) *MockRedisServiceInterface_GetStatistics_Call {
	return &MockRedisServiceInterface_GetStatistics_Call{Call: _e.mock.On("GetStatistics", ctx)}
}

func (_c *MockRedisServiceInterface_GetStatistics_Call) Run(run func(ctx context.Context)) *MockRedisServiceInterface_GetStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRedisServiceInterface_GetStatistics_Call) Return(redisMetricsResponse *models.RedisMetricsResponse, err error) *MockRedisServiceInterface_GetStatistics_Call {
	_c.Call.Return(redisMetricsResponse, err)
	return _c
}

func (_c *MockRedisServiceInterface_GetStatistics_Call) RunAndReturn(run func(ctx context.Context) (*models.RedisMetricsResponse, error)) *MockRedisServiceInterface_GetStatistics_Call {
	_c.Call.Return(run)
	return _c
}
