// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kafka_mocks

import (
	"delivery-system/internal/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProducerInterface creates a new instance of MockProducerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProducerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProducerInterface {
	mock := &MockProducerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProducerInterface is an autogenerated mock type for the ProducerInterface type
type MockProducerInterface struct {
	mock.Mock
}

type MockProducerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProducerInterface) EXPECT() *MockProducerInterface_Expecter {
	return &MockProducerInterface_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockProducerInterface
func (_mock *MockProducerInterface) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProducerInterface_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockProducerInterface_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockProducerInterface_Expecter) Close() *MockProducerInterface_Close_Call {
	return &MockProducerInterface_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockProducerInterface_Close_Call) Run(run func()) *MockProducerInterface_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProducerInterface_Close_Call) Return(err error) *MockProducerInterface_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProducerInterface_Close_Call) RunAndReturn(run func() error) *MockProducerInterface_Close_Call {
	_c.Call.Return(run)
	return _c
}

// PublishCourierAssigned provides a mock function for the type MockProducerInterface
func (_mock *MockProducerInterface) PublishCourierAssigned(orderID uuid.UUID, courierID uuid.UUID) error {
	ret := _mock.Called(orderID, courierID)

	if len(ret) == 0 {
		panic("no return value specified for PublishCourierAssigned")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(orderID, courierID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProducerInterface_PublishCourierAssigned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishCourierAssigned'
type MockProducerInterface_PublishCourierAssigned_Call struct {
	*mock.Call
}

// PublishCourierAssigned is a helper method to define mock.On call
//   - orderID uuid.UUID
//   - courierID uuid.UUID
func (_e *MockProducerInterface_Expecter) PublishCourierAssigned(orderID interface{}, courierID interface{}) *MockProducerInterface_PublishCourierAssigned_Call {
	return &MockProducerInterface_PublishCourierAssigned_Call{Call: _e.mock.On("PublishCourierAssigned", orderID, courierID)}
}

func (_c *MockProducerInterface_PublishCourierAssigned_Call) Run(run func(orderID uuid.UUID, courierID uuid.UUID)) *MockProducerInterface_PublishCourierAssigned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProducerInterface_PublishCourierAssigned_Call) Return(err error) *MockProducerInterface_PublishCourierAssigned_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProducerInterface_PublishCourierAssigned_Call) RunAndReturn(run func(orderID uuid.UUID, courierID uuid.UUID) error) *MockProducerInterface_PublishCourierAssigned_Call {
	_c.Call.Return(run)
	return _c
}

// PublishCourierStatusChanged provides a mock function for the type MockProducerInterface
func (_mock *MockProducerInterface) PublishCourierStatusChanged(courierID uuid.UUID, oldStatus models.CourierStatus, newStatus models.CourierStatus) error {
	ret := _mock.Called(courierID, oldStatus, newStatus)

	if len(ret) == 0 {
		panic("no return value specified for PublishCourierStatusChanged")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, models.CourierStatus, models.CourierStatus) error); ok {
		r0 = returnFunc(courierID, oldStatus, newStatus)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProducerInterface_PublishCourierStatusChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishCourierStatusChanged'
type MockProducerInterface_PublishCourierStatusChanged_Call struct {
	*mock.Call
}

// PublishCourierStatusChanged is a helper method to define mock.On call
//   - courierID uuid.UUID
//   - oldStatus models.CourierStatus
//   - newStatus models.CourierStatus
func (_e *MockProducerInterface_Expecter) PublishCourierStatusChanged(courierID interface{}, oldStatus interface{}, newStatus interface{}) *MockProducerInterface_PublishCourierStatusChanged_Call {
	return &MockProducerInterface_PublishCourierStatusChanged_Call{Call: _e.mock.On("PublishCourierStatusChanged", courierID, oldStatus, newStatus)}
}

func (_c *MockProducerInterface_PublishCourierStatusChanged_Call) Run(run func(courierID uuid.UUID, oldStatus models.CourierStatus, newStatus models.CourierStatus)) *MockProducerInterface_PublishCourierStatusChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 models.CourierStatus
		if args[1] != nil {
			arg1 = args[1].(models.CourierStatus)
		}
		var arg2 models.CourierStatus
		if args[2] != nil {
			arg2 = args[2].(models.CourierStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProducerInterface_PublishCourierStatusChanged_Call) Return(err error) *MockProducerInterface_PublishCourierStatusChanged_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProducerInterface_PublishCourierStatusChanged_Call) RunAndReturn(run func(courierID uuid.UUID, oldStatus models.CourierStatus, newStatus models.CourierStatus) error) *MockProducerInterface_PublishCourierStatusChanged_Call {
	_c.Call.Return(run)
	return _c
}

// PublishLocationUpdated provides a mock function for the type MockProducerInterface
func (_mock *MockProducerInterface) PublishLocationUpdated(courierID uuid.UUID, lat float64, lon float64) error {
	ret := _mock.Called(courierID, lat, lon)

	if len(ret) == 0 {
		panic("no return value specified for PublishLocationUpdated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, float64, float64) error); ok {
		r0 = returnFunc(courierID, lat, lon)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProducerInterface_PublishLocationUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishLocationUpdated'
type MockProducerInterface_PublishLocationUpdated_Call struct {
	*mock.Call
}

// PublishLocationUpdated is a helper method to define mock.On call
//   - courierID uuid.UUID
//   - lat float64
//   - lon float64
func (_e *MockProducerInterface_Expecter) PublishLocationUpdated(courierID interface{}, lat interface{}, lon interface{}) *MockProducerInterface_PublishLocationUpdated_Call {
	return &MockProducerInterface_PublishLocationUpdated_Call{Call: _e.mock.On("PublishLocationUpdated", courierID, lat, lon)}
}

func (_c *MockProducerInterface_PublishLocationUpdated_Call) Run(run func(courierID uuid.UUID, lat float64, lon float64)) *MockProducerInterface_PublishLocationUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProducerInterface_PublishLocationUpdated_Call) Return(err error) *MockProducerInterface_PublishLocationUpdated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProducerInterface_PublishLocationUpdated_Call) RunAndReturn(run func(courierID uuid.UUID, lat float64, lon float64) error) *MockProducerInterface_PublishLocationUpdated_Call {
	_c.Call.Return(run)
	return _c
}

// PublishOrderCreated provides a mock function for the type MockProducerInterface
func (_mock *MockProducerInterface) PublishOrderCreated(order *models.Order) error {
	ret := _mock.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for PublishOrderCreated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Order) error); ok {
		r0 = returnFunc(order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProducerInterface_PublishOrderCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishOrderCreated'
type MockProducerInterface_PublishOrderCreated_Call struct {
	*mock.Call
}

// PublishOrderCreated is a helper method to define mock.On call
//   - order *models.Order
func (_e *MockProducerInterface_Expecter) PublishOrderCreated(order interface{}) *MockProducerInterface_PublishOrderCreated_Call {
	return &MockProducerInterface_PublishOrderCreated_Call{Call: _e.mock.On("PublishOrderCreated", order)}
}

func (_c *MockProducerInterface_PublishOrderCreated_Call) Run(run func(order *models.Order)) *MockProducerInterface_PublishOrderCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Order
		if args[0] != nil {
			arg0 = args[0].(*models.Order)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProducerInterface_PublishOrderCreated_Call) Return(err error) *MockProducerInterface_PublishOrderCreated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProducerInterface_PublishOrderCreated_Call) RunAndReturn(run func(order *models.Order) error) *MockProducerInterface_PublishOrderCreated_Call {
	_c.Call.Return(run)
	return _c
}

// PublishOrderStatusChanged provides a mock function for the type MockProducerInterface
func (_mock *MockProducerInterface) PublishOrderStatusChanged(orderID uuid.UUID, oldStatus models.OrderStatus, newStatus models.OrderStatus, courierID *uuid.UUID) error {
	ret := _mock.Called(orderID, oldStatus, newStatus, courierID)

	if len(ret) == 0 {
		panic("no return value specified for PublishOrderStatusChanged")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, models.OrderStatus, models.OrderStatus, *uuid.UUID) error); ok {
		r0 = returnFunc(orderID, oldStatus, newStatus, courierID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProducerInterface_PublishOrderStatusChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishOrderStatusChanged'
type MockProducerInterface_PublishOrderStatusChanged_Call struct {
	*mock.Call
}

// PublishOrderStatusChanged is a helper method to define mock.On call
//   - orderID uuid.UUID
//   - oldStatus models.OrderStatus
//   - newStatus models.OrderStatus
//   - courierID *uuid.UUID
func (_e *MockProducerInterface_Expecter) PublishOrderStatusChanged(orderID interface{}, oldStatus interface{}, newStatus interface{}, courierID interface{}) *MockProducerInterface_PublishOrderStatusChanged_Call {
	return &MockProducerInterface_PublishOrderStatusChanged_Call{Call: _e.mock.On("PublishOrderStatusChanged", orderID, oldStatus, newStatus, courierID)}
}

func (_c *MockProducerInterface_PublishOrderStatusChanged_Call) Run(run func(orderID uuid.UUID, oldStatus models.OrderStatus, newStatus models.OrderStatus, courierID *uuid.UUID)) *MockProducerInterface_PublishOrderStatusChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 models.OrderStatus
		if args[1] != nil {
			arg1 = args[1].(models.OrderStatus)
		}
		var arg2 models.OrderStatus
		if args[2] != nil {
			arg2 = args[2].(models.OrderStatus)
		}
		var arg3 *uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProducerInterface_PublishOrderStatusChanged_Call) Return(err error) *MockProducerInterface_PublishOrderStatusChanged_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProducerInterface_PublishOrderStatusChanged_Call) RunAndReturn(run func(orderID uuid.UUID, oldStatus models.OrderStatus, newStatus models.OrderStatus, courierID *uuid.UUID) error) *MockProducerInterface_PublishOrderStatusChanged_Call {
	_c.Call.Return(run)
	return _c
}
